- name: Setup PostgreSQL
  hosts: localhost
  tasks:
    - name: Check if PostgreSQL service exists
      command: systemctl is-active postgresql
      register: postgresql_status

    - name: Start PostgreSQL service if it exists
      command: systemctl start postgresql
      when: postgresql_status.rc == 0

    - name: Enable PostgreSQL service
      command: systemctl enable postgresql
      when: postgresql_status.rc == 0

    - name: Wait for PostgreSQL to start
      wait_for:
        timeout: 300
        host: localhost
        port: 5432
      when: postgresql_status.rc == 0

    - name: Check PostgreSQL status
      command: pg_isready
      register: postgresql_check
      changed_when: false
      failed_when: postgresql_check.rc != 0

    - name: Inform about PostgreSQL setup
      debug:
        msg: 'PostgreSQL successfully set up.'
      when: postgresql_check.rc == 0

    - name: Inform about missing PostgreSQL service
      debug:
        msg: 'PostgreSQL service not found. Skipping setup.'
      when: postgresql_check.rc != 0

- import_playbook: postgres-playbook.yml

- name: Setup Redis
  hosts: localhost
  tasks:
    - name: Check if Redis service exists
      command: systemctl is-active redis
      register: redis_status

    - name: Start Redis service if it exists
      command: systemctl start redis
      when: redis_status.rc == 0

    - name: Enable Redis service
      command: systemctl enable redis
      when: redis_status.rc == 0

    - name: Wait for Redis to start
      wait_for:
        timeout: 30
        host: localhost
        port: 6379
      when: redis_status.rc == 0

    - name: Check Redis status
      command: redis-cli ping
      register: redis_check
      changed_when: false
      failed_when: redis_check.rc != 0

    - name: Inform about Redis setup
      debug:
        msg: 'Redis successfully set up.'
      when: redis_check.rc == 0

    - name: Inform about missing Redis service
      debug:
        msg: 'Redis service not found. Skipping setup.'
      when: redis_check.rc != 0

- import_playbook: redis-playbook.yml

- name: Configure NestJS Application
  hosts: localhost
  roles:
    - install-nodejs
    - pre-nestjs
    - nestjs-deploy
    - nestjs-service-setup
