- name: Setup PostgreSQL
  hosts: localhost
  tasks:
    - name: Ensure PostgreSQL is running
      service:
        name: postgresql
        state: started
      register: pg_service
      until: pg_service is succeeded
      retries: 5
      delay: 5

- import_playbook: postgres-playbook.yml

- name: Setup Redis
  hosts: localhost
  tasks:
    - name: Ensure Redis is running
      service:
        name: redis
        state: started

- import_playbook: redis-playbook.yml

- name: Configure NestJS Application
  hosts: localhost
  roles:
    - install-nodejs
    - pre-nestjs
    - nestjs-deploy
    - nestjs-service-setup
    - nestjs-ouath-token
