---
- name: Print Minikube IP and Database Connection Details
  hosts: minikube
  tasks:
    - name: Print Minikube IP
      debug:
        msg: "Minikube IP is {{ ansible_host }}"

    - name: Verify inventory_hostname
      debug:
        msg: "Current host is: {{ hostvars[inventory_hostname]['db_user'] }}"

    - name: Print Database Connection Details
      debug:
        msg:
          - "Database Host: {{ db_host }}"
          - "Database Port: {{ db_port }}"
          - "Database User: {{ db_user }}"
          - "Database Password: {{ db_password }}"
          - "Database Name: {{ db_name }}"

- hosts: localhost
  name: Deploy NestJS application
  roles:
    - test
    - pre-nestjs
    - install-nodejs
    - nestjs-deploy
    - nestjs-service-setup
    - postgresql
    - redis
