---
- name: Deploy NestJS application
  hosts: localhost
  roles:
    - postgresql
    - redis
    - nestjs-config
    - nestjs-deploy
    - pre-nestjs
    # - install-nodejs
    # - nestjs-deploy
    # - nestjs-service-setup
