---
- name: Full Deployment of NestJS Application
  hosts: localhost
  roles:
    - portals

- name: Setup PostgreSQL
  hosts: localhost
  tasks:
    - name: Ensure PostgreSQL is running
      service:
        name: postgresql
        state: started

- import_playbook: postgres-playbook.yml

- name: Setup Redis
  hosts: localhost
  tasks:
    - name: Ensure Redis is running
      service:
        name: redis
        state: started

- import_playbook: redis-playbook.yml

- name: Configure NestJS Application
  hosts: localhost
  roles:
    - install-nodejs
    - pre-nestjs
    - nestjs-deploy
    - nestjs-service-setup
    - nestjs-auth-token
