- name: Full Deployment of NestJS Application
  hosts: localhost
  become: yes
  roles:
    - portals

- name: Setup PostgreSQL
  hosts: localhost
  tasks:
    - import_playbook: postgresql-playbook.yml

- name: Ensure PostgreSQL is running
  service:
    name: postgresql
    state: started

- name: Setup Redis
  hosts: localhost
  tasks:
    - import_playbook: redis-playbook.yml

- name: Ensure Redis is running
  service:
    name: redis
    state: started

- name: Configure NestJS Application
  hosts: localhost
  become: yes
  roles:
    - install-node
    - pre-nestjs
    - nestjs
    - service_setup
    - auth_token
