mytenants:
  - namespace: "portal1"
    portals:
      - name: "portal1"
        jwt_token_secret: "secret1"
        jwt_access_token_ttl: "3600"
        jwt_refresh_token_ttl: "7200"
      - name: "portal2"
        jwt_token_secret: "secret2"
        jwt_access_token_ttl: "3600"
        jwt_refresh_token_ttl: "7200"
  - namespace: "tenant2"
    portals:
      - name: "portal3"
        jwt_token_secret: "secret3"
        jwt_access_token_ttl: "3600"
        jwt_refresh_token_ttl: "7200"