---
- name: Set facts for mytenants
  set_fact:
    mytenants: 
      - namespace: "portal1"
        portals:
          - name: "nestjs-auth"
            replicacount: 1
        mytenantname: "first_tenant"
      - namespace: "portal2"
        portals:
          - name: "another-auth"
            replicacount: 2
        mytenantname: "second_tenant"

- name: Debug mytenants variable
  debug:
    var: mytenants

- name: Render tenant configuration
  template:
    src: mytenants.j2
    dest: /tmp/{{ item.namespace }}_mytenants.yaml
  loop: "{{ mytenants }}"
  vars:
    tenant: "{{ item }}"