---
- set_fact:
    mytenants:
      - namespace: portal1
        portals:
          - name: 'nestjs-auth'
            replicacount: 1
        mytenantname: first_tenant

# - name: Create Kubernetes namespace for each tenant
#   community.kubernetes.k8s:
#     state: present
#     definition:
#       apiVersion: v1
#       kind: Namespace
#       metadata:
#         name: "{{ item.namespace }}"
#   loop: "{{ mytenants }}"
#   loop_control:
#     loop_var: item
#   register: namespace_creation_results

# - name: Log namespace creation results
#   debug:
#     var: namespace_creation_results

- name: Apply MyPortal CRD YAML to Kubernetes cluster
  community.kubernetes.k8s:
    definition: "{{ lookup('file', '../../config/samples/portal1_mytenants.yaml') | from_yaml }}"
    state: present
  loop: "{{ mytenants }}"
  loop_control:
    loop_var: item

# - name: Apply MyPortal CRD YAML to Kubernetes cluster
#   community.kubernetes.k8s:
#     definition: "{{ lookup('template', '/myportal/config/samples/portal1_mytenants.yaml') | from_yaml }}"
#     state: present
#   loop: "{{ mytenants }}"
#   loop_control:
#     loop_var: item