---
- name: Set facts for mytenants
  set_fact:
    mytenants: "{{ lookup('file', 'mytenants.yml') | from_yaml }}"

- name: Debug mytenants variable
  debug:
    var: mytenants

- name: Render mytenants YAML for each tenant
  template:
    src: mytenants.j2
    dest: "/tmp/{{ item.namespace }}_mytenants.yaml"  # Unique file per tenant
    vars:
      tenant: "{{ item }}"
  loop: "{{ mytenants }}"