---
- set_fact:
    mytenants:
      - namespace: portal1
        portals:
          - name: 'nestjs-auth'
            replicacount: 1
        mytenantname: first_tenant

- name: Create Kubernetes namespace for each tenant
  community.kubernetes.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ item.namespace }}"
  loop: "{{ mytenants }}"
  loop_control:
    loop_var: item
  register: namespace_creation_results

- name: Log namespace creation results
  debug:
    var: namespace_creation_results

- name: Generate MyPortal YAML files for each tenant
  copy:
    dest: "/myk8sansible/myportal/config/samples/{{ item.namespace }}_mytenants.yaml"
    content: |
      apiVersion: myportal/v1
      kind: MyPortal
      metadata:
        name: "{{ item.mytenantname }}"
      spec:
        portals:
          {% for portal in item.portals %}
          - name: "{{ portal.name }}"
            replicacount: {{ portal.replicacount }}
          {% endfor %}
  loop: "{{ mytenants }}"
  loop_control:
    loop_var: item

- name: Apply MyPortal CRD YAML to Kubernetes cluster
  community.kubernetes.k8s:
    definition: "{{ lookup('file', '/myk8sansible/myportal/config/samples/' + item.namespace + '_mytenants.yaml') | from_yaml }}"
    state: present
  loop: "{{ mytenants }}"
  loop_control:
    loop_var: item