---
- name: Set facts for mytenants
  set_fact:
    mytenants: 
      - namespace: "portal1"
        portals:
          - name: "nestjs-auth"
            replicacount: 1
        mytenantname: "first_tenant"
      - namespace: "portal2"
        portals:
          - name: "another-auth"
            replicacount: 2
        mytenantname: "second_tenant"

- name: Debug mytenants variable
  debug:
    var: mytenants

- name: Render tenant configurations to separate files
  template:
    src: mytenant.j2
    dest: "/tmp/{{ tenant.namespace }}.yaml"
  loop: "{{ mytenants }}"
  loop_control:
    loop_var: tenant