apiVersion: portal.mycourse1.com/v1
kind: MyPortal
metadata:
  name: "{{ namespace }}"
  namespace: "{{ namespace }}"
spec:
  myportals:
    - name: "{{ portal.name }}"
      replicacount: "{{ portal.replicacount }}"
  mytenantname: "{{ mytenantname | default('default_value') }}"