apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ portalname }}"
  namespace: portal1
spec:
  selector:
    matchLabels:
      app: "{{ portalname }}-deploy"
  template:
    metadata:
      labels:
        app: "{{ portalname }}-deploy"
  spec:
    containers:
      - name: nestjs-auth
        image: "nestjs-auth:V1"
        ports:
          - containerPort: 3000
        securityContext:
          runAsUser: 1003

        envFrom:
          - configMapRef:
              name: jwt-configmap
          - configMapRef:
              name: postgresql-configmap
    resources:
      requests:
        memory: "128Mi"
        cpu: "250m"
      limits:
        memory: "256Mi"
        cpu: "500m"

    volumes:
      - name: jwt-secrets
        secret:
          secretName: jwt-secrets
