apiVersion: apps/v1
kind: Deployment
metadata:
  name: '{{ portalname }}'
  namespace: '{{ namespace }}'
spec:
  selector:
    matchLabels:
      app: '{{ portalname }}-deploy'
  template:
    metadata:
      labels:
        app: '{{ portalname }}-deploy'
  spec:
    containers:
      - name: nestjs-auth
        image:
        ports:
          - containerPort: 3000
        securityContext:
          runAsUser: 1003
        volumeMounts:
          - name: jwt-secrets
            mountPath: /etc/jwt-secrets
          - name: nestjs-volume
            mountPath: /nestjs
        env:
          - name: REDIS_HOST
            value: 'redis'
          - name: REDIS_PORT
            value: '6379'
          - name: JWT_TOKEN_SECRET
            value: "{{ jwt_token_secret | default('secret1') }}"
          - name: JWT_ACCESS_TOKEN_TTL
            value: "{{ jwt_access_token_ttl | default('3600') }}"
          - name: JWT_REFRESH_TOKEN_TTL
            value: "{{ jwt_refresh_token_ttl | default('86400') }}"
          - name: JWT_TOKEN_AUDIENCE
            value: '{{ portalname }}.default.svc.cluster.local'
          - name: JWT_TOKEN_ISSUER
            value: '{{ portalname }}.default.svc.cluster.local'
          - name: POSTGRES_USERNAME
            value: 'postgres'
          - name: POSTGRES_PASSWORD
            value: 'pass123'
          - name: POSTGRES_DATABASE
            value: 'postgres'
          - name: POSTGRES_HOST
            value: 'postgres'
          - name: POSTGRES_PORT
            value: '5432'
        envFrom:
          - secretRef:
              name: jwt-secrets
            prefix: JWT_
          - configMapRef:
              name: postgresql-configmap
    resources:
      requests:
        memory: '128Mi'
        cpu: '250m'
      limits:
        memory: '256Mi'
        cpu: '500m'
    readinessProbe:
      httpGet:
        path: /health
        port: 3000
      initialDelaySeconds: 10
      periodSeconds: 5
    livenessProbe:
      httpGet:
        path: /health
        port: 3000
      initialDelaySeconds: 30
      periodSeconds: 10
    volumes:
      - name: jwt-secrets
        secret:
          secretName: jwt-secrets
