apiVersion: v1
kind: Secret
metadata:
  name: jwt-secrets
  namespace: '{{ namespace }}'
type: Opaque
data:
  JWT_TOKEN_SECRET: '{{ jwt_token_secret | b64encode }}' # Ensure this variable is defined
  JWT_ACCESS_TOKEN_TTL: '{{ jwt_access_token_ttl | b64encode }}' # Ensure this variable is defined
  JWT_REFRESH_TOKEN_TTL: '{{ jwt_refresh_token_ttl | b64encode }}' # Ensure this variable is defined
