---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: '{{ portalname }}-pvc'
  namespace: '{{ namespace }}'
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
