apiVersion: v1
kind: PersistentVolume
metadata:
  name: "{{ portalname }}-pv"
  namespace: "{{ namespace }}"
spec:
  capacity:
    storage: 1Gi # Adjust the size according to your needs
  accessModes:
    - ReadWriteMany
  hostPath: # For local development; adjust for cloud providers
    path: /mnt/nestjs
