apiVersion: v1
kind: PersistentVolume
metadata:
  name: "{{ portalname }}-pv"  # Use portalname variable for dynamic naming
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/data/{{ portalname }}
