apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ portalname }}runner
  namespace: {{ namespace }}
spec:
  replicas: {{ replicacount }}
  selector:
    matchLabels:
      app: {{ portalname }}
  template:
    metadata:
      labels:
        app: {{ portalname }}
    spec:
      initContainers:
        - name: init-secrets
          image: busybox
          command:
            - sh
            - -c
            - |
              set -e  # Exit on error
              cp /etc/secrets/jwt-secrets.env /root/nestjs/.env.jwt
              cp /etc/secrets/postgresql-secret.env /root/nestjs/.env.postgres
          volumeMounts:
            - name: jwt-secrets
              mountPath: /etc/secrets
            - name: postgresql-secret
              mountPath: /etc/secrets
            - name: app-volume
              mountPath: /root/nestjs
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000

      containers:
        - name: {{ portalname }}-c
          image: ubuntu:latest
          command:
            - /bin/sh
          args:
            - -c
            - |
              set -e  # Exit on error
              echo "${ARCHIVE_CONTENT}" | base64 --decode > /root/nestjs-app-archive.tar.gz
              tar xzf /root/nestjs-app-archive.tar.gz -C /root
              cd /root/nestjs
              ansible-playbook playbooks/nestjs-playbook.yml || { echo "Ansible playbook failed"; exit 1; }
          env:
            - name: REDIS_HOST
              value: "redis"  
            - name: REDIS_PORT
              value: "6379"
            - name: JWT_TOKEN_AUDIENCE
              value: "{{ portalname }}.default.svc.cluster.local" 
            - name: JWT_TOKEN_ISSUER
              value: "{{ portalname }}.default.svc.cluster.local"
          envFrom:
            - secretRef:
                name: jwt-secrets
              prefix: JWT_
            - secretRef:
                name: postgresql-secret
              prefix: POSTGRES_
          volumeMounts:
            - name: app-volume
              mountPath: /root
            - name: jwt-secrets
              mountPath: /root/nestjs/.env.jwt
              subPath: .env.jwt
            - name: postgresql-secret
              mountPath: /root/nestjs/.env.postgres
              subPath: .env.postgres
          resources:
            requests:
              memory: '128Mi'
              cpu: '250m'
            limits:
              memory: '256Mi'
              cpu: '500m'
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 15  # Adjusted based on typical startup times
            periodSeconds: 5
            timeoutSeconds: 2  # Increased timeout
            successThreshold: 1
            failureThreshold: 3

      volumes:
        - name: app-volume
          configMap: 
            name: {{ portalname }}-cm
        - name: jwt-secrets
          secret:
            secretName: jwt-secrets
        - name: postgresql-secret
          secret:
            secretName: postgresql-secret