apiVersion: v1
kind: Service
metadata:
  namespace: "{{ namespace }}"
  name: "{{ portalname }}"
  labels:
    app: "{{ portalname }}"
spec:
  selector:
    app: "{{ portalname }}-deploy" # Adjusted to match the Deployment label
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
