apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{ { mytenantname } }"
  namespace: "{ { namespace } }"
  annotations:

  rules:
    - host: "{ { mytenantname } }"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nestjs-auth
                port:
                  number: 80
