apiVersion: v1
kind: PersistentVolume
metadata:
  name: app-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /myk8sansible/myportal/roles/nestjs-deploy/templates/nestjs-pvc.yml # Change this to your desired path on the host
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-pvc
  namespace: { { namespace } } # Ensure it matches your deployment namespace
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
