apiVersion: v1
kind: Service
metadata:
  namespace: { { namespace } }
  name: { { portalname } }
spec:
  selector:
    app: { { portalname } }
  ports:
    - protocol: TCP
      port: { { portal.port_mapping.external } }
      targetPort: { { portal.port_mapping.internal } }
