apiVersion: v1
kind: Service
metadata:
  namespace: { { namespace } }
  name: { { portalname } }
spec:
  selector:
    app: { { portalname } }
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
