apiVersion: v1
kind: Service
metadata:
  namespace: { { namespace } } # Removed spaces
  name: { { portalname } } # Removed spaces
  labels:
    app: { { portalname } } # Removed spaces
spec:
  selector:
    app: { { portalname } } # Removed spaces
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP # Specify the service type if needed, defaults to ClusterIP
