apiVersion: v1
kind: Secret
metadata:
  name: {{ item.name }}
  namespace: portal1  # Set the namespace here
type: Opaque
data:
  JWT_TOKEN_SECRET: {{ jwt_token_secret | b64encode }}  # Ensure this variable is defined
  JWT_ACCESS_TOKEN_TTL: {{ jwt_access_token_ttl | b64encode }}  # Ensure this variable is defined
  JWT_REFRESH_TOKEN_TTL: {{ jwt_refresh_token_ttl | b64encode }}  # Ensure this variable is defined