apiVersion: v1
kind: Service
metadata:
  namespace: { { namespace } }
  name: { { portalname } }
  labels:
    app: { { portalname } } # Adding labels for better identification
spec:
  selector:
    app: { { portalname } }
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP # Specify the service type if needed, defaults to ClusterIP
