apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-configmap
  namespace: portal1
data:
  POSTGRES_HOST: 'postgres'
  POSTGRES_PORT: '5432'
  POSTGRES_USER: 'postgres'
  POSTGRES_PASSWORD: 'pass123'
  POSTGRES_DB: 'postgres'
