apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ portalname}}
  labels:
    app: {{portalname }} # Adding labels for better identification
  namespace: {{ namespace }}
spec:
  rules:
    - host: first-tenant # Ensure this is a valid hostname
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ portalname }} # Should point to the service name
                port:
                  number: 80 # Should point to the service port, which is 80