apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ portalname }}
  namespace: {{ namespace }}
spec:
  replicas: {{ replicacount }}
  selector:
    matchLabels:
      app: {{ portalname }}
  template:
    metadata:
      labels:
        app: {{ portalname }}
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
      initContainers:
        - name: init-secrets
          image: busybox
          command:
            - sh
            - -c
            - |
              set -e
              # Copy JWT secrets
              for key in $(ls /etc/jwt-secrets); do
                cp "/etc/jwt-secrets/$key" "/root/nestjs/.env.jwt"
              done

              # Create a tarball of the necessary files
              tar czf /root/nestjs/init/nestjs-app-archive.tar.gz -C /root/nestjs . || { echo "Failed to create tarball"; exit 1; }

              # Log success
              echo "JWT secrets copied and tarball created successfully."

              # Change ownership of the entire /root/nestjs directory
              chown -R 1000:1000 /root/nestjs

              # Change ownership of specific files
              chown -R 1000:1000 /root/nestjs/.env.jwt
              chown -R 1000:1000 /root/nestjs/.env.postgres
              chown -R 1000:1000 /root/nestjs/init/nestjs-app-archive.tar.gz
              chown -R 1000:1000 /root/nestjs/init

              # Attempt to remount the filesystem as read-write
              mount -o remount,rw /

      containers:
        - name: {{ portalname }}
          image: ubuntu:latest
          command:
            - /bin/sh
          args:
            - -c
            - |
              set -e
              echo "Creating init directory..."
              mkdir -p /root/nestjs/init

              echo "Creating tarball..."
              tar czf /root/nestjs/init/nestjs-app-archive.tar.gz -C /root/nestjs . || { echo "Failed to create tarball"; exit 1; }

              echo "Contents of /root/nestjs/init:"
              ls -l /root/nestjs/init

              if [ ! -f /root/nestjs/init/nestjs-app-archive.tar.gz ]; then
                echo "Error: Tarball not found at /root/nestjs/init/nestjs-app-archive.tar.gz"
                exit 1
              fi

              echo "Extracting tarball..."
              tar xzf /root/nestjs/init/nestjs-app-archive.tar.gz -C /root/nestjs || { echo "Failed to extract tarball"; exit 1; }
              cd /root/nestjs
              ansible-playbook playbooks/nestjs.yml || { echo "Ansible playbook failed"; exit 1; }
          env:
            - name: REDIS_HOST
              value: 'redis'
            - name: REDIS_PORT
              value: '6379'
            - name: JWT_TOKEN_AUDIENCE
              value: '{{ portalname }}.default.svc.cluster.local'
            - name: JWT_TOKEN_ISSUER
              value: '{{ portalname }}.default.svc.cluster.local'
          envFrom:
            - secretRef:
                name: jwt-secrets
              prefix: JWT_
            - secretRef:
                name: postgresql-secret
              prefix: POSTGRES_
          volumeMounts:
            - name: init-volume
              mountPath: /root/nestjs/init
              securityContext:
                fsGroup: 1000
            - name: jwt-secrets
              mountPath: /root/nestjs/.env.jwt
              subPath: jwt-secrets.env
              securityContext:
                fsGroup: 1000
            - name: postgresql-secret
              mountPath: /root/nestjs/.env.postgres
              subPath: postgresql-secret.env
              securityContext:
                fsGroup: 1000
            - name: data-volume
              mountPath: /data
              securityContext:
                fsGroup: 1000
          resources:
            requests:
              memory: '128Mi'
              cpu: '250m'
            limits:
              memory: '256Mi'
              cpu: '500m'
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 5
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 3

      volumes:
        - name: init-volume
          persistentVolumeClaim:
            claimName: "{{ portalname }}-pvc"
        - name: jwt-secrets
          secret:
            secretName: jwt-secrets
        - name: postgresql-secret
          secret:
            secretName: postgresql-secret
        - name: data-volume
          emptyDir: {}