apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: first-tenant
  namespace: portal1
  annotations:

  rules:
    - host: first-tenant
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nestjs-auth
                port:
                  number: 80
