apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ portalname }}
  namespace: {{ namespace }}
spec:
  replicas: {{ replicacount }}
  selector:
    matchLabels:
      app: {{ portalname }}
  template:
    metadata:
      labels:
        app: {{ portalname }}
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
        readOnlyRootFilesystem: false
      initContainers:
        - name: init-secrets
          image: busybox
          command:
            - sh
            - -c
            - |
              set -e
              mkdir -p /tmp/nestjs
              for key in JWT_ACCESS_TOKEN_TTL JWT_REFRESH_TOKEN_TTL JWT_TOKEN_SECRET; do
                if [ -f /etc/jwt-secrets/$key ]; then
                  cp /etc/jwt-secrets/$key /tmp/nestjs/.env.jwt
                else
                  echo "Error: /etc/jwt-secrets/$key not found."
                  exit 1
                fi
              done
              tar czf /tmp/nestjs/nestjs-app-archive.tar.gz -C /tmp/nestjs . || { echo "Failed to create tarball"; exit 1; }
              mv /tmp/nestjs/nestjs-app-archive.tar.gz /tmp/nestjs/ || { echo "Failed to move tarball"; exit 1; }
              echo "JWT secrets copied and tarball created successfully."
          volumeMounts:
            - name: jwt-secrets
              mountPath: /etc/jwt-secrets
            - name: init-volume
              mountPath: /tmp/nestjs  # Updated to a writable path

      containers:
        - name: {{ portalname }}
          image: ubuntu:latest
          command:
            - /bin/sh
          args:
            - -c
            - |
              set -e
              # Ensure ownership is correct
              chown -R 1000:1000 /root/nestjs
              echo "Contents of /root/nestjs:"
              ls -l /root/nestjs
              if [ ! -f /root/nestjs/nestjs-app-archive.tar.gz ]; then
                echo "Error: Tarball not found at /root/nestjs/nestjs-app-archive.tar.gz"
                exit 1
              fi
              tar xzf /root/nestjs/nestjs-app-archive.tar.gz -C /root/nestjs || { echo "Failed to extract tarball"; exit 1; }
              cd /root/nestjs
              ansible-playbook playbooks/nestjs.yml || { echo "Ansible playbook failed"; exit 1; }
          envFrom:
            - secretRef:
                name: jwt-secrets
              prefix: JWT_
            - secretRef:
                name: postgresql-secret
              prefix: POSTGRES_
          volumeMounts:
            - name: init-volume
              mountPath: /root/nestjs
            - name: jwt-secrets
              mountPath: /root/nestjs/.env.jwt
              subPath: jwt-secrets.env
            - name: postgresql-secret
              mountPath: /root/nestjs/.env.postgres
              subPath: postgresql-secret.env
            - name: data-volume
              mountPath: /data
          resources:
            requests:
              memory: '128Mi'
              cpu: '250m'
            limits:
              memory: '256Mi'
              cpu: '500m'
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 5
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 3

      volumes:
        - name: init-volume
          persistentVolumeClaim:
            claimName: "{{ portalname }}-pvc"
        - name: jwt-secrets
          secret:
            secretName: jwt-secrets
        - name: postgresql-secret
          secret:
            secretName: postgresql-secret
        - name: data-volume
          emptyDir: {}