---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-pvc
  namespace: { { namespace } } # Ensure it matches your deployment namespace
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
