apiVersion: v1
kind: PersistentVolume
metadata:
  name: '{{ portalname }}-pv'
  namespace: '{{ namespace }}'
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: 'manual'
  hostPath:
    path: /mnt/nestjs
