---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ portalname }}-pvc"  # Use portalname variable for dynamic naming
  namespace: "{{ namespace }}"     # Ensure it matches your deployment namespace
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
