apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ mytenantname }}
  namespace: {{ namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2  
spec:
  rules:
  - host: {{ mytenantname }}
    http:
      paths:
{% for dict_item in myportals %}
      - path: /{{ dict_item.name }}(/|$)(.*)
        pathType: Prefix      
        backend:
          service: 
            name: {{ dict_item.name }}ser
            port : 
              number: 9091
{% endfor %}


