apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ portalname }}deploy
  namespace: {{ namespace }}
spec:
  replicas: {{ replicacount }}
  selector:
    matchLabels:
      app: {{ portalname }}
  template:
    metadata:
      labels:
        app: {{ portalname }}
    spec:
      containers:
      - name: {{ portalname }}c
        image: httpd:latest
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - name: html
            mountPath: /usr/local/apache2/htdocs
      volumes:
      - name: html
        configMap:
          name: {{ portalname }}cm

