mytenants:
  - namespace: "portal1"
    myportals:
      - name: "nestjs-auth"
        jwt_token_secret: "secret1"
        jwt_access_token_ttl: "3600"
        jwt_refresh_token_ttl: "7200"
        replicacount: 1
        POSTGRES_HOST: "postgres"
        POSTGRES_PORT: "5432"
        POSTGRES_USERNAME: "postgres"
        POSTGRES_PASSWORD: "pass123"
        POSTGRES_DATABASE: "postgres"
