- name: Create Kubernetes namespace for each tenant
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ item.namespace }}"
  loop: "{{ mytenants }}"
  delegate_to: localhost