---
# 1. Clone or update the NestJS repository
- name: Clone or update the NestJS repository
  git:
    repo: "{{ repo_path }}"
    dest: "{{ service_path }}"
    version: main
    update: yes
    force: yes
  register: repo_clone
  delegate_to: localhost

# 2. Ensure correct permissions for /nestjs
- name: Ensure /nestjs has correct permissions
  file:
    path: "/nestjs"
    mode: "u=rwx,g=rx,o=rx"
  become: true

# 3. Synchronize MyK8sAnsible folder to myk8sansible/myportal
- name: Synchronize MyK8sAnsible folder to /myk8sansible/myportal/
  synchronize:
    src: "{{ service_path }}/myportal/"
    dest: "/myk8sansible/myportal/"
    delete: yes

# 4. Set Docker environment to Minikube's Docker daemon
- name: Set Docker environment to Minikube's Docker daemon
  shell: |
    eval $(minikube -p minikube docker-env)
  environment:
    DOCKER_CLI_EXPERIMENTAL: "enabled"
  become: true

- name: Create a Dockerfile for the NestJS app
  copy:
    dest: "{{ dockerfile_path }}"
    content: |
      # Use Node.js base image
      FROM node:20 alpine

      # Set working directory
      WORKDIR /app

      # Copy package.json and package-lock.json
      COPY package*.json ./

      # Install dependencies
      RUN npm install

      # Copy the rest of the application
      COPY . .

      # Expose the application port
      EXPOSE 3000

      # Run the NestJS application
      CMD ["npm", "run", "start:prod"]

- name: Build Docker image for NestJS app
  community.docker.docker_image:
    name: "nestjs-auth"
    build:
      path: "{{ service_path }}"
    tag: "V1"
    state: present
    docker_host: "tcp://192.168.49.2:2376"

- name: Ensure Docker image is built and available
  docker_image_info:
