---
- name: Set tenant name and portals data
  set_fact:
    mytenantname: "tenant1" # Set this to your tenant name or a specific identifier
    myportals:
      - {
          name: "nestjs-auth",
          replicacount: 1,
          namespace: portal1,
          image: "nestjs-auth:V1",
        }

# 1. Clone or update the NestJS repository
- name: Clone or update the NestJS repository
  git:
    repo: "{{ repo_path }}"
    dest: "{{ service_path }}"
    version: main
    update: yes
    force: yes
  register: repo_clone

# 2. Ensure correct permissions for /nestjs
- name: Ensure /nestjs has correct permissions
  file:
    path: "/nestjs"
    mode: "u=rwx,g=rx,o=rx"
  become: true

# 3. Synchronize MyK8sAnsible folder to /myk8sansible/myportal/
- name: Synchronize MyK8sAnsible folder to /myk8sansible/myportal/
  synchronize:
    src: "{{ service_path }}/myportal/"
    dest: "/myk8sansible/myportal/"
    delete: yes

# 5. Create a Dockerfile for the NestJS app
- name: Create a Dockerfile for the NestJS app
  copy:
    dest: "{{ dockerfile_path }}"
    content: |
      # Use Node.js base image
      FROM node:20

      # Set working directory
      WORKDIR /app

      # Copy package.json and package-lock.json
      COPY package*.json ./

      # Install dependencies
      RUN npm install

      # Copy the rest of the application
      COPY . .

      # Expose the application port
      EXPOSE 3000

      # Run the NestJS application
      CMD ["npm", "run", "start:prod"]

  # Step 1: Find containers using the nestjs-auth:V1 image
- name: Find containers using the nestjs-auth:V1 image
  command: docker ps -a --filter "ancestor=nestjs-auth:V1" --format "{{.ID}}"
  register: containers_using_image
  changed_when:
    false

    # Step 2: Stop containers using the nestjs-auth:V1 image
- name: Stop containers using the nestjs-auth:V1 image
  command: docker stop "{{ item }}"
  with_items: "{{ containers_using_image.stdout_lines }}"
  when:
    containers_using_image.stdout_lines | length > 0

    # Step 3: Remove containers using the nestjs-auth:V1 image
- name: Remove containers using the nestjs-auth:V1 image
  command: docker rm "{{ item }}"
  with_items: "{{ containers_using_image.stdout_lines }}"
  when: containers_using_image.stdout_lines | length > 0

  # Step 4: Remove the old NestJS image
- name: Remove old NestJS image
  community.docker.docker_image:
    name: "nestjs-auth"
    tag: "V1"
    state: absent

- name: Build Docker image for NestJS app
  community.docker.docker_image:
    name: "nestjs-auth"
    source: build
    build:
      path: "{{ service_path }}"
    tag: "V1"
    state: present
    force: yes # Forces a rebuild even if the image already exists

# 7. Verify Docker image availability in Minikube
- name: Verify Docker image availability in Minikube
  shell: |
    docker images | grep "nestjs-auth"
  register: docker_images
  failed_when: "'nestjs-auth' not in docker_images.stdout"

- name: Set image_tag fact for deployment
  set_fact:
    image_tag: "nestjs-auth:V1"

- name: Print the image tag (for verification)
  debug:
    msg: "The image tag for deployment is: {{ image_tag }}"

# Loop through myportals to deploy both ConfigMap (postgresql and jwt) and application Deployment
- name: Deploy ConfigMaps and application for each portal
  block:
    - name: Deploy the PostgreSQL ConfigMap for "{{ item.name }}"
      kubernetes.core.k8s:
        state: present
        definition: |
          apiVersion: v1
          kind: ConfigMap
          metadata:
            name: "{{ item.name }}-configmap"
            namespace: "{{ ansible_operator_meta.namespace }}"
          data:
            POSTGRES_HOST: 'postgres.portal1.svc.cluster.local'
            POSTGRES_PORT: '5432'
            POSTGRES_USER: 'postgres'
            POSTGRES_PASSWORD: 'pass123'
            POSTGRES_DB: 'postgres'
      loop: "{{ myportals }}"

    - name: Deploy the JWT ConfigMap for "{{ item.name }}"
      kubernetes.core.k8s:
        state: present
        definition: |
          apiVersion: v1
          kind: ConfigMap
          metadata:
            name: "{{ item.name }}-jwt-configmap"
            namespace: "{{ ansible_operator_meta.namespace }}"
          data:
            JWT_TOKEN_SECRET: 'secret'
            JWT_ACCESS_TOKEN_TTL: '3600'
            JWT_REFRESH_TOKEN_TTL: '7600'
            JWT_TOKEN_AUDIENCE: "{{ item.name }}.default.svc.cluster.local"
      loop: "{{ myportals }}"

    - name: Deploy the application using kubernetes.core.k8s for "{{ item.name }}"
      kubernetes.core.k8s:
        state: present
        definition: |
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: "{{ item.name }}-deployment"
            namespace: "{{ ansible_operator_meta.namespace }}"
          spec:
            replicas: {{ item.replicacount | default(1) }}
            selector:
              matchLabels:
                app: "{{ item.name }}"
            template:
              metadata:
                labels:
                  app: "{{ item.name }}"
              spec:
                containers:
                  - name: "{{ item.name }}"
                    image: "{{ item.image | default('nestjs-auth:V1') }}"
                    imagePullPolicy: Always
                    ports:
                      - containerPort: 3000
                    env:
                      - name: POSTGRES_HOST
                        valueFrom:
                          configMapKeyRef:
                            name: "{{ item.name }}-configmap"
                            key: POSTGRES_HOST
                      - name: POSTGRES_PORT
                        valueFrom:
                          configMapKeyRef:
                            name: "{{ item.name }}-configmap"
                            key: POSTGRES_PORT
                      - name: POSTGRES_USER
                        valueFrom:
                          configMapKeyRef:
                            name: "{{ item.name }}-configmap"
                            key: POSTGRES_USER
                      - name: POSTGRES_PASSWORD
                        valueFrom:
                          configMapKeyRef:
                            name: "{{ item.name }}-configmap"
                            key: POSTGRES_PASSWORD
                      - name: POSTGRES_DB
                        valueFrom:
                          configMapKeyRef:
                            name: "{{ item.name }}-configmap"
                            key: POSTGRES_DB
                      - name: JWT_TOKEN_SECRET
                        valueFrom:
                          configMapKeyRef:
                            name: "{{ item.name }}-jwt-configmap"
                            key: JWT_TOKEN_SECRET
                      - name: JWT_ACCESS_TOKEN_TTL
                        valueFrom:
                          configMapKeyRef:
                            name: "{{ item.name }}-jwt-configmap"
                            key: JWT_ACCESS_TOKEN_TTL
                      - name: JWT_REFRESH_TOKEN_TTL
                        valueFrom:
                          configMapKeyRef:
                            name: "{{ item.name }}-jwt-configmap"
                            key: JWT_REFRESH_TOKEN_TTL
                      - name: JWT_TOKEN_AUDIENCE
                        valueFrom:
                          configMapKeyRef:
                            name: "{{ item.name }}-jwt-configmap"
                            key: JWT_TOKEN_AUDIENCE
                    resources:
                      requests:
                        memory: "512Mi"
                        cpu: "500m"
                      limits:
                        memory: "1Gi"
                        cpu: "1"
      loop: "{{ myportals }}"

    - name: Deploy Service for "{{ item.name }}"
      kubernetes.core.k8s:
        state: present
        definition: |
          apiVersion: v1
          kind: Service
          metadata:
            namespace: "{{ ansible_operator_meta.namespace }}"
            name: "{{ item.name }}"
            labels:
              app: "{{ item.name }}"
          spec:
            selector:
              app: "{{ item.name }}"  # Ensure this matches the deployment label
            ports:
              - protocol: TCP
                port: 80
                targetPort: 3000
            ClusterIP: none
      loop: "{{ myportals }}"
