# Create destination directory (if it doesn't exist)
- name: Create destination directory
  file:
    path: "{{ service_path }}"
    state: directory
  become: true

# Clone or update the NestJS repository
- name: Clone or update the NestJS repository
  git:
    repo: "{{ repo_path }}"
    dest: "{{ service_path }}"
    version: main
    update: yes
    force: yes
  register: repo_clone
  delegate_to: localhost
  become: true

# Synchronize MyK8sAnsible folder to /myk8sansible/myportal
- name: Synchronize MyK8sAnsible folder to /myk8sansible/myportal
  rsync:
    src: "{{ service_path }}/myportal"
    dest: "/myk8sansible/myportal"
    delete: yes
    rsync_opts:
      - "--ignore-perms"
      - "--chmod=ugo-rwx"
  when: repo_clone.changed

# Synchronize MyK8sAnsible folder to /mnt/nestjs
- name: Synchronize MyK8sAnsible folder to /mnt/nestjs
  rsync:
    src: "{{ service_path }}"
    dest: "/mnt/nestjs"
    rsync_opts:
      - "--exclude=myportal"
    delete: yes
  when: repo_clone.changed
