
---
- name: Clone or update the NestJS repository
  ansible.builtin.git:
    repo: '{{ repo_path }}'
    dest: '{{ service_path }}'
    version: main
    update: yes
  register: repo_clone
  changed_when: repo_clone.changed

- name: Fail if cloning or updating the repository failed
  ansible.builtin.fail:
    msg: 'Failed to clone or update the repository.'
  when: repo_clone is failed

- name: Pull latest changes from the main branch
  ansible.builtin.command:
    cmd: |
      git -C '{{ service_path }}' pull origin main
    creates: '{{ service_path }}/HEAD'
  register: git_pull
  changed_when: git_pull.rc == 0

- name: Check if pulling changes was successful
  ansible.builtin.fail:
    msg: 'Failed to pull changes from the repository.'
  when: git_pull.rc != 0

- name: Check for changes in the repository
  ansible.builtin.command:
    cmd: |
      git -C '{{ service_path }}' status --porcelain
    creates: '{{ service_path }}/HEAD'
  register: git_status
  changed_when: false
  failed_when: false

- name: Determine if there are changes in the main branch
  ansible.builtin.set_fact:
    has_changes: "{{ git_status.stdout != '' }}"

- name: Check if myportal folder exists
  ansible.builtin.stat:
    path: /opt/nestjs/myportal
  register: stat

- name: Ensure destination directory exists
  ansible.builtin.file:
    path: /Myk8sAnsible/myportal
    state: directory
    create: yes
  register: dir_check
  changed_when: dir_check.changed

- name: Fail if directory creation failed
  ansible.builtin.fail:
    msg: 'Failed to create the directory.'
  when: dir_check is failed

- name: Synchronize Myk8sAnsible folder to the correct location
  ansible.builtin.command:
    cmd: |
      rsync --delay-updates -F --compress --delete-after --archive
      /opt/nestjs/ ../../
    creates: /Myk8sAnsible/myportal
  register: rsync_result
  changed_when: rsync_result.rc == 0

- name: Report rsync failure
  ansible.builtin.debug:
    msg: "Rsync failed with error: {{ rsync_result.stderr }}"
  when: rsync_result.rc != 0

- name: Check if the archive already exists
  ansible.builtin.stat:
    path: /tmp/nestjs-app-archive.tar.gz
  register: archive_stat

- name: Remove existing archive if it exists
  ansible.builtin.file:
    path: /tmp/nestjs-app-archive.tar.gz
    state: absent
  when: archive_stat.stat.exists and has_changes

- name: Archive NestJS application excluding Myk8sAnsible
  ansible.builtin.archive:
    path: /opt/nestjs
    exclude_path: /opt/nestjs/myportal
    dest: /tmp/nestjs-app-archive.tar.gz
    format: gz
  when: has_changes

- name: Encode archive content in base64
  ansible.builtin.set_fact:
    base64_content: "{{ lookup('pipe', 'base64 /tmp/nestjs-app-archive.tar.gz') }}"
  when: has_changes

- name: Display encoded archive content
  ansible.builtin.debug:
    msg: '{{ base64_content }}'
  when: has_changes