apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: first-tenant
  namespace: portal1
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - host: first-tenant
      http:
        paths:
          - path: /nestjs-auth/
            pathType: Prefix
            backend:
              service:
                name: nestjs-auth
                port:
                  number: 80
