---

- name: Create Redis Deployment
  community.kubernetes.k8s:
    definition: "{{ lookup('template', 'redis-deployment.yml') | from_yaml }}"
    state: present

- name: Create Redis Service
  community.kubernetes.k8s:
    definition: "{{ lookup('template', 'redis-service.yml') | from_yaml }}"
    state: present

