# permissions for end users to view myportals.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: myportal-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: myportal
    app.kubernetes.io/part-of: myportal
    app.kubernetes.io/managed-by: kustomize
  name: myportal-viewer-role
rules:
- apiGroups:
  - portal.mycourse1.com
  resources:
  - myportals
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - portal.mycourse1.com
  resources:
  - myportals/status
  verbs:
  - get
