yaml
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
  ##
  ## Base operator rules
  ##
  - apiGroups:
      - ""
      - "extensions"
      - "networking.k8s.io"
    resources:
      - secrets
      - pods
      - pods/exec
      - pods/log
      - services
      - serviceaccounts
      - configmaps
      - ingresses/status
      - ingresses
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - apps
    resources:
      - deployments
      - daemonsets
      - replicasets
      - statefulsets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  ##
  ## Rules for portal.mycourse1.com/v1, Kind: MyPortal
  ##
  - apiGroups:
      - portal.mycourse1.com
    resources:
      - myportals
      - myportals/status
      - myportals/finalizers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  ##
  ## Permissions for Postgres
  ##
  - apiGroups:
      - apps
    resources:
      - statefulsets
      - statefulsets/status
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  ##
  ## Permissions for Redis
  ##
  - apiGroups:
      - apps
    resources:
      - statefulsets
      - statefulsets/status
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  ##
  ## Permissions for NestJS
  ##
  - apiGroups:
      - apps
    resources:
      - deployments
      - deployments/status
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
# +kubebuilder:scaffold:rules
