apiVersion: v1
kind: Service
metadata:
  name: {{ portalname }}ser
  namespace: {{ namespace }}
spec:
  ports:
  - port: 9091
    targetPort: 80
    protocol: TCP
  selector:
    app: {{ portalname }}

