apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-configmap
  namespace: namespace: "{{ ansible_operator_meta.namespace | default('default') }}"
data:
  POSTGRES_DB: postgres
  POSTGRES_HOST: postgres
  POSTGRES_PORT: "5432"