apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: portal1
spec:
  selector:
    app: postgres # Ensure this matches the labels in your PostgreSQL pod
  ports:
    - protocol: TCP
      port: 5432 # Port exposed by the Service
      targetPort: 5432 # Port on the PostgreSQL Pod

selector:
  app: postgres
