apiVersion: v1
kind: Service
metadata:
  name: postgres # The name you will use in the NestJS app to connect to PostgreSQL
  namespace: portal1
spec:
  selector:
    app: postgres # Match the label of your PostgreSQL pod here
  ports:
    - protocol: TCP
      port: 5432 # Default PostgreSQL port
      targetPort: 5432 # The port PostgreSQL listens to inside the container
  clusterIP: None # Internal service within the cluster
