apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: portal1
spec:
  serviceName: "postgres"
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: postgresql-configmap
                  key: POSTGRES_DB
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgresql-configmap
                  key: POSTGRES_HOST
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgresql-configmap
                  key: POSTGRES_PORT
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: postgresql-configmap # Changed to use ConfigMap
                  key: POSTGRES_PASSWORD # Ensure this key exists in your ConfigMap
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: postgresql-configmap # Changed to use ConfigMap
                  key: POSTGRES_USER # Ensure this key exists in your ConfigMap
  volumeClaimTemplates:
    - metadata:
        name: postgres-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi
