apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-configmap
  namespace: "{{ namespace }}"
data:
  POSTGRES_DB: "{{ db_database }}" # Ensure this variable is defined
  POSTGRES_HOST: "{{ db_host }}" # Ensure this variable is defined
  POSTGRES_PORT: "{{ db_port }}" # Ensure this variable is defined

