# apiVersion: v1
# kind: Secret
# metadata:
#   name: postgresql-secret
#   namespace: "{{ namespace }}"
# type: Opaque
# data:
#   db_password: "{{ db_password | b64encode }}" # Ensure this variable is defined
#   db_username: "{{ db_username | b64encode }}"
