- name: Deploy NestJS Application
  hosts: localhost
  vars:
    service_path: '/opt/nestjs'
    repo_path: 'https://github.com/Simeon-muyiwa/Nest-auth'

  tasks:
    - name: Clone or update the NestJS repository
      git:
        repo: '{{ repo_path }}'
        dest: '{{ service_path }}'
        version: main
        update: yes
      register: repo_clone
      failed_when: "'fatal:' in repo_clone.stderr | default('', true) or repo_clone.rc != 0"
      changed_when: repo_clone.changed

    - name: Check if Myk8sAnsible folder exists
      ansible.builtin.stat:
        path: /opt/nestjs/Myk8sAnsible
      register: stat

    - name: Move the Myk8sAnsible folder if it exists
      command: >
        mv /opt/nestjs/Myk8sAnsible /desired/location/
      when: stat.stat.exists

    - name: Archive NestJS application excluding Myk8sAnsible
      archive:
        path: /opt/nestjs
        exclude_path: /opt/nestjs/Myk8sAnsible
        dest: /tmp/nestjs-app-archive.tar.gz
        format: gz

    - name: Encode archive content in base64
      set_fact:
        base64_content: "{{ lookup('pipe', 'base64 /tmp/nestjs-app-archive.tar.gz') }}"

    - name: Create ConfigMap manifest from template
      ansible.builtin.template:
        src: configmap_template.yaml.j2
        dest: /tmp/configmap.yaml
      vars:
        base64_content: '{{ base64_content }}'

    - name: Display ConfigMap manifest
      ansible.builtin.debug:
        msg: "{{ lookup('file', '/tmp/configmap.yaml') }}"
