---
# tasks:

- name: Sign Up and Obtain Tokens
  ansible.builtin.uri:
    url: "http://first-tenant/authentication/sign-up"
    method: POST
    body:
      username: "{{ signup_username }}"
      password: "{{ signup_password }}"
    body_format: json
    return_content: yes
  register: signup_response
  failed_when: signup_response.status != 200
# - name: Sign Up and Obtain Tokens
#   ansible.builtin.uri:
#     url: http://first-tenant/authentication/sign-up
#     method: POST
#     body:
#       username: "muyiwa"
#       password: "simeon"
#     body_format: json
#     return_content: yes
#   register: signup_response
#   failed_when: "'token' not in signup_response.json or 'refresh_token' not in signup_response.json"

# - name: Extract Auth and Refresh Tokens
#   set_fact:
#     auth_token: "{{ signup_response.json.token }}"
#     refresh_token: "{{ signup_response.json.refresh_token }}"

# - name: Make a GET request with Bearer token
#   ansible.builtin.uri:
#     url: http://first-tenant/authentication/sign-in
#     method: GET
#     headers:
#       Authorization: "Bearer {{ auth_token }}"
#     return_content: yes
#   register: get_api_response
#   failed_when: get_api_response.status != 200

# - name: Print the API response
#   ansible.builtin.debug:
#     msg: "{{ get_api_response.content }} (Status: {{ get_api_response.status }})"
# - name: Refresh Auth Token
#   ansible.builtin.uri:
#     url: http://localhost/authentication/refresh
#     method: POST
#     body:
#       refresh_token: "{{ refresh_token }}"
#     body_format: json
#     return_content: yes
#   register: refresh_response
#   failed_when: "'token' not in refresh_response.json"

# - name: Extract New Auth Token
#   set_fact:
#     auth_token: "{{ refresh_response.json.token }}"

# - name: Make a POST request with Bearer token and JSON payload
#   ansible.builtin.uri:
#     url: http://localhost/coffee
#     method: POST
#     headers:
#       Authorization: "Bearer {{ auth_token }}"
#       Content-Type: "application/json"
#     body:
#       key: "value"
#     body_format: json
#     return_content: yes
#   register: post_api_response
#   failed_when: post_api_response.status != 200

# - name: Print the API response
#   ansible.builtin.debug:
#     msg: "{{ post_api_response.content }} (Status: {{ post_api_response.status }})"
