---
# tasks file for myk8sansible
- name: Deploy ConfigMap
  community.kubernetes.k8s:
    definition: "{{ lookup('template', 'nestjs-configmap.yml', template_vars=dict(portalname=item.name, namespace=ansible_operator_meta.namespace, base64_content=base64_content)) | from_yaml }}"
    state: present
  loop: '{{ mytenantname }}'

- name: Create nestjs Secret
  community.kubernetes.k8s:
    definition: "{{ lookup('template', 'nestjs-secret-env.yml', template_vars=dict(portalname=item.name, namespace=ansible_operator_meta.namespace)) | from_yaml }}"
    state: present
  loop: '{{ mytenantname }}'

- name: Create nestjs deployments/replicasets and pods
  community.kubernetes.k8s:
    definition: "{{ lookup('template', 'nestjs-deploy.yml', template_vars=dict(portalname=item.name, namespace=ansible_operator_meta.namespace, replicacount=item.replicacount)) | from_yaml }}"
    state: present
  loop: '{{ mytenantname }}'
- name: Create nestjs services
  community.kubernetes.k8s:
    definition: "{{ lookup('template', 'nestjs-service.yml', template_vars=dict(portalname=item.name, namespace=ansible_operator_meta.namespace)) | from_yaml }}"
    state: present
  loop: '{{ mytenantname }}'
- name: Create nestjs ingress
  community.kubernetes.k8s:
    definition: "{{ lookup('template', 'nestjs-ingress.yml', template_vars=dict(namespace=ansible_operator_meta.namespace)) | from_yaml }}"
    state: present
