---
- name: Get MyPortal custom resource
  community.kubernetes.k8s_info:
    kind: MyPortal
    namespace: portal1
  register: myportal_info

- name: Check if any MyPortal resources were found
  fail:
    msg: "No MyPortal resources found."
  when: myportal_info.resources | length == 0

- name: Set myportals variable
  set_fact:
    myportals: "{{ myportal_info.resources[0].spec.myportals }}"

- name: Debug myportals variable
  debug:
    var: myportals

- name: Create Persistent Volume for each portal
  community.kubernetes.k8s:
    definition: "{{ lookup('template', 'nestjs-pv.yml', template_vars=dict(portalname=item.name, namespace=ansible_operator_meta.namespace)) | from_yaml }}"
    state: present
  loop: "{{ myportals }}"
