- name: Install service dependencies
  community.general.npm:
    path: "{{ service_path }}"
    state: present

- name: Build the service
  community.general.npm:
    path: "{{ service_path }}"
    run_script: build

- name: Start the service
  ansible.builtin.command: npm run start --prefix "{{ service_path }}"
  async: 180
  poll: 0