---
    - name: Install service dependencies
      npm:
        path: "{{ service_path }}"
        state: present

    - name: Build the NestJS service
      command: npm run build
      args:
        chdir: "{{ service_path }}"
      register: build_result

    - name: Ensure build was successful
      fail:
        msg: "Build failed with error code: {{ build_result.rc }}"
      when: build_result.rc != 0

    - name: Start the NestJS service
      command: npm run start
      args:
        chdir: "{{ service_path }}"
      register: start_result

    - name: Show result of service start
      debug:
        var: start_result