- name: Install service dependencies
  community.general.npm:
    path: "{{ service_path }}"
    state: present

- name: Build the NestJS service
  command: npm run build
  args:
    chdir: /opt/nestjs

- name: Start the service
  ansible.builtin.command: npm run start --prefix "{{ service_path }}"
  async: 180
  poll: 0