
---
- name: Update and upgrade APT packages
  apt:
    update_cache: yes
    upgrade: dist

- name: Clean up APT cache
  apt:
    autoclean: yes

- name: Ensure curl is installed
  apt:
    name: curl
    state: present

- name: Add GPG key for Node.js
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present

- name: Add Node.js repository
  apt_repository:
    repo: "deb https://deb.nodesource.com/node {{ lookup('url', 'https://deb.nodesource.com/distros.json') | regex_search('Ubuntu\\s+Focal\\s+(\\d+)') | capture }}"
    state: present
    update_cache: yes

- name: Install build dependencies
  apt:
    name:
      - build-essential
      - libssl-dev
    state: present

- name: Install Node.js and npm
  apt:
    name:
      - nodejs
      - npm
    state: present
    install_recommends: yes