---

- name: Update and upgrade APT packages
  apt:
    update_cache: yes
    upgrade: dist

- name: Clean up APT cache
  apt:
    autoclean: yes

- name: Add GPG key for Node.js
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present

- name: Add Node.js repository
  command: curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
  args:
    warn: false

- name: Install Node.js and npm
  apt:
    name:
      - nodejs
      - npm
    state: present
    install_recommends: yes