apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: portal1
spec:
  clusterIP: None # Headless service
  selector:
    app: redis
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
