apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: "{{ ansible_operator_meta.namespace | default('default') }}"
spec:
  clusterIP: None # Headless service
  selector:
    app: redis
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
